# Generated by Django 4.2 on 2023-05-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wapp',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wapp',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wapp',
            name='weather_desc',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
