# Generated by Django 4.2 on 2023-05-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0002_wapp_humidity_wapp_temp_wapp_weather_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wapp',
            name='weather_desc',
        ),
    ]
